services:
  mariadb:
    image: mariadb
    restart: always
    environment:
      MARIADB_ROOT_PASSWORD: 1234
      MARIADB_DATABASE: mydb
    ports:
      - "3306:3306"
    volumes:
      - mariadb_data:/var/lib/mysql
      - ../database/init_db.sql:/docker-entrypoint-initdb.d/init_db.sql

  fastapi:
    build:
      context: ../back
      dockerfile: docker/Dockerfile
    ports:
      - "8000:8000"
    depends_on:
      - mariadb

volumes:
  mariadb_data:
