services:
  mariadb:
    image: mariadb
    environment:
      MARIADB_ROOT_PASSWORD: 1234
      MARIADB_DATABASE: mydb
    ports:
      - "55555:3306"
    volumes:
      - mariadb_data:/var/lib/mysql
    networks:
      - guardias
  fastapi:
    build:
      context: ../back
      dockerfile: docker/Dockerfile
    ports:
      - "8000:8000"
    depends_on:
      - mariadb
    networks:
      - guardias


volumes:
  mariadb_data:
networks:
  guardias:
