-- MySQL Script generated by MySQL Workbench
-- Sun Apr  7 16:48:58 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering
SET SQL_MODE='';
SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';


-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`roles`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`roles` ;

CREATE TABLE IF NOT EXISTS `mydb`.`roles` (
  `codigo` VARCHAR(15) NOT NULL,
  PRIMARY KEY (`codigo`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`profesores`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`profesores` ;

CREATE TABLE IF NOT EXISTS `mydb`.`profesores` (
  `id` VARCHAR(64) NOT NULL,
  `nick` VARCHAR(45) NOT NULL,
  `color` VARCHAR(7) NULL,
  `rol` VARCHAR(15) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `rol_profesor_idx` (`rol` ASC) VISIBLE,
  CONSTRAINT `rol_profesor`
    FOREIGN KEY (`rol`)
    REFERENCES `mydb`.`roles` (`codigo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`ausencias`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`ausencias` ;

CREATE TABLE IF NOT EXISTS `mydb`.`ausencias` (
  `id` INT NOT NULL,
  `fecha` DATE NOT NULL,
  `hora` ENUM("1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15") NOT NULL,
  `id_profesor_ausente` VARCHAR(64) NOT NULL,
  `id_profesor_suplente` VARCHAR(64) NULL,
  PRIMARY KEY (`id`),
  INDEX `id_profesor_ausente_idx` (`id_profesor_ausente` ASC) VISIBLE,
  INDEX `id_profesor_suplente_idx` (`id_profesor_suplente` ASC) VISIBLE,
  CONSTRAINT `id_profesor_ausente`
    FOREIGN KEY (`id_profesor_ausente`)
    REFERENCES `mydb`.`profesores` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `id_profesor_suplente`
    FOREIGN KEY (`id_profesor_suplente`)
    REFERENCES `mydb`.`profesores` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`ciclos`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`ciclos` ;

CREATE TABLE IF NOT EXISTS `mydb`.`ciclos` (
  `codigo` VARCHAR(15) NOT NULL,
  `nombre` VARCHAR(25) NOT NULL,
  PRIMARY KEY (`codigo`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`asignaturas`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`asignaturas` ;

CREATE TABLE IF NOT EXISTS `mydb`.`asignaturas` (
  `codigo` VARCHAR(15) NOT NULL,
  `codigo_ciclo` VARCHAR(15) NOT NULL,
  `nombre` VARCHAR(45) NOT NULL,
  `aula` VARCHAR(15) NULL,
  PRIMARY KEY (`codigo`),
  INDEX `id_codigo_ciclo_idx` (`codigo_ciclo` ASC) VISIBLE,
  CONSTRAINT `id_codigo_ciclo`
    FOREIGN KEY (`codigo_ciclo`)
    REFERENCES `mydb`.`ciclos` (`codigo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`profesor_imparte_asignatura`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`profesor_imparte_asignatura` ;

CREATE TABLE IF NOT EXISTS `mydb`.`profesor_imparte_asignatura` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `id_profesor` VARCHAR(64) NOT NULL,
  `id_asignatura` VARCHAR(15) NOT NULL,
  `dia_semana` VARCHAR(9) NOT NULL,
  `hora` ENUM("1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15") NOT NULL,
  `habilitado` TINYINT(1) NOT NULL,
  INDEX `id_asignatura_es_impartida_idx` (`id_asignatura` ASC) VISIBLE,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `unique_habilitado_no_repetido` (`id_profesor` ASC, `id_asignatura` ASC, `dia_semana` ASC, `hora` ASC, `habilitado` ASC) VISIBLE,
  CONSTRAINT `id_profesor_imparte`
    FOREIGN KEY (`id_profesor`)
    REFERENCES `mydb`.`profesores` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `id_asignatura_es_impartida`
    FOREIGN KEY (`id_asignatura`)
    REFERENCES `mydb`.`asignaturas` (`codigo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`historial_habilitado_asignaturas_impartidas`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`historial_habilitado_asignaturas_impartidas` ;

CREATE TABLE IF NOT EXISTS `mydb`.`historial_habilitado_asignaturas_impartidas` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `id_profesor_imparte_asignatura` INT NOT NULL,
  `id_habilitado` VARCHAR(15) NOT NULL,
  `dia_modificacion` DATE NOT NULL,
  `antiguo_valor` TINYINT(1) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `id_profesor_asignatura_habilitado_modificada_idx` (`id_profesor_imparte_asignatura` ASC) VISIBLE,
  CONSTRAINT `id_profesor_asignatura_habilitado_modificada`
    FOREIGN KEY (`id_profesor_imparte_asignatura`)
    REFERENCES `mydb`.`profesor_imparte_asignatura` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
